#! /bin/bash -eu

export GOPATH=`pwd`

come_deps.sh

PROJECT=shoreline

OUTDIR=dist
rm -rf ${OUTDIR}
mkdir ${OUTDIR}

go build -o ${OUTDIR}/${PROJECT}
go build -o ${OUTDIR}/user-roles tools/user-roles.go

cp start.sh ${OUTDIR}/
