#! /bin/bash -eu

TESTDIRS=$(find . -name "*_test.go" -and ! -path "./Godeps/*" |sed s@/[^/]*go@@ |sed s@./@@ |uniq)

for i in $TESTDIRS; do
    echo Testing in $i:
    cd $i
    godep go test -v
    cd ..
done
